profiles:
  development:
    base_url: http://nick-harvey.github.io/
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: gh-pages
      # use master branch for <username>.github.io repository
      branch: master
  production:
    base_url: http://commons.openshift.org/
    deploy:
      host: commons-originsites.rhcloud.com
      path: /var/lib/openshift/54d9249c4382ec277000003b/app-root/data/html
